### PR TITLE
Added changes for handling password string for UserIdentityToken and …

### PR DESCRIPTION
**Pull request by jchirantan**
…for private key in case of certificate based connections to prevent it's trace in memory

### CODE REVIEW

**Review by jouniaro — CHANGES_REQUESTED** [review]
Thanks for the suggestions.

A couple of things I would do differently.

1) You could use Arrays.fill to reset the char arrays in a more neat way.

2) java.util.Base64 is not available in Java 6 - and the stack is still based on that. But we have CryptoUtil.base64encode and base64decode that you can use, instead.

**Comment by jchirantan** [comment]
Hi @jouniaro 
When I use CryptoUtil.base64decode, I can see occurrences of Password String in memory dump. Can you suggest some other option?

**Comment by pradeipk** [comment]
Hi @jouniaro, Any update on above query. Also Is there any plan to migrate to higher version of JDK?

**Comment by jouniaro** [comment]
You should probably add an overload to base64Decode that takes char[] instead of String.

The stack is not under active development anymore and therefore there is no plan to update to higher JDK.

**Comment by jchirantan** [comment]
Hi @jouniaro I have made the changes in the PR as suggested by you. 
Please review the changed PR...

**Comment by jchirantan** [comment]
Hi @jouniaro , Any updates on the PR?

**Comment by jouniaro** [comment]
Actually, the base64Decode that takes the 'char[]' still creates a String from of it. I think you would like to prevent that as well.

**Comment by jchirantan** [comment]
Hi @jouniaro, Thanks for your suggestion
- I will try to overload "loadFromKeyStore" function as per your suggestion
- Also, can you suggest how we can prevent creation of String from char[] in Base64.decode() method which is inside bouncycastle library?

**Comment by jchirantan** [comment]
Hi @jouniaro, any updates?

**Comment by jouniaro** [comment]
Base64 encoding is not secure encoding and OPC UA does not specify it to be used for passwords. OPC UA specifies secure encoding of passwords, if a proper security policy is defined. So we don't want to add any non-standard Base64 decoding in there either. Therefore, if you want to use Base64 for handling passwords internally in your client or server application, it is better to do it outside the stack, but the stack should only handle plain text and then use the defined encryption policies.

If you wish avoid Strings with Base64 encoded, you should use the 'byte[]' version of the APIs. If you wish to add support for that to the SDK, you would need to add the respective overload to CryptoProvider, CertificateProvider and CertificateUtils, which all have the base64Decode method (for certain reasons). The implementation for the BC versions, for example, would look like this:

	@Override
	public byte[] base64Decode(byte[] bytes) {
		return Base64.decode(bytes);
	}

As to how to convert char[] to byte[], refer to this [StackOverflow question](https://stackoverflow.com/questions/5513144/converting-char-to-byte), for example.

**Comment by jchirantan** [comment]
Hi @jouniaro, 
- I have removed Base64 encoding and decoding part from code as per your suggestions
- Also, introduced overloaded methods to accept password in character array format
- I have kept overloaded methods for base64Decode() to pass character array as input instead of String, in CryptoProvider, CertificateProvider, CertificateUtils, BcCryptoProvider, ScCryptoProvider, BcCertificateProvider, ScCertificateProvider(Whichever classes have base64Decode method and the methods which call base64Decode method) as mentioned by you, for future reference.
- Please review the PR

**Comment by jouniaro** [comment]
Yeah, looks better in general. Would be better to make the 'string' versions of the functions call the 'char []' versions, to avoid two complete copies of the same functions, though. Could you do that as well?

**Comment by jchirantan** [comment]
Hi @jouniaro,
Thanks for your reply.
I have made the changes suggested by you. 
Can you please review the PR now?

**Comment by jchirantan** [comment]
Hi @jouniaro,
Any updates on PR?

**Comment by jouniaro** [comment]
I reviewed the code and made still some changes to clarify it. And it didn't compile :)

Please, verify my commit yourself and create a new PR, if OK for you.

**Comment by jchirantan** [comment]
Hi @jouniaro,
I will implement the changes suggested by you and will raise another PR.
Closing this PR now

**Pull request closed without merging**
